# Automatically generated by GPRPy
import gprpy.gprpy as gp
mygpr = gp.gprpyProfile()
mygpr.importdata('../../data/GPR/line1.dt1')
mygpr.setZeroTime(7.5)
#mygpr.dewow(100)
mygpr.tpowGain(2)
#mygpr.agcGain(100)
mygpr.setVelocity(0.08)
mygpr.topoCorrect('../../data/GPR/profile_horizontal.txt',delimiter='\t')
mygpr.printProfile('200MHz_raw_vel0.08.pdf', color='bwr', contrast=20, yrng=[-3,5], xrng=[0,58.9], dpi=600, asp=1)
# For dewow, make contrast 20
